image:
  name: docker/compose:1.25.4
  entrypoint: [""]

variables:
  GIT_STRATEGY: clone
  DOCKER_DRIVER: overlay2
  DOCKER_COMPOSE: >-
    docker-compose
    --project-name $CI_JOB_NAME-$CI_COMMIT_SHA-$CI_JOB_ID
    --file docker-compose_ci.yml
  DOCKER_CONTAINERS: docker ps -aq -f name=$CI_JOB_NAME-$CI_COMMIT_SHA-$CI_JOB_ID

before_script:
  - echo "SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI" >> .env
  - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
  - export DOCKER_BUILDKIT=1

stages:
  - build
  - test

build:
  stage: build
  script:
    - ${DOCKER_COMPOSE} build api

test:
  stage: test
  script:
    - ${DOCKER_COMPOSE} up --detach
    - ${DOCKER_COMPOSE} exec -T api pytest

after_script:
  - ${DOCKER_COMPOSE} down --volumes
