version: '3'
services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres_data_ci:/var/lib/postgresql/data
    api:
        build: .
        container_name: api
        command:
            - flask run --host=0.0.0.0
        entrypoint:
            - bash
            - -c
            - wait-for-it --service db:5432 -t 120 -- $$@
            - sh
        ports:
            - 5000:5000
        environment:
            - SQLALCHEMY_TRACK_MODIFICATIONS=False
        env_file:
            - .env
        depends_on:
            - db

volumes:
    postgres_data_ci:
        driver: local
